### ISSUE TITLE
Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by baixiaoyu2997** [meteorlxy/vuepress-theme-meteorlxy#6]
1. bug:
如果md文章没有设置title部分可能会导致build报错,下边是报错信息
```sh
TypeError: Cannot read property 'path' of undefined
    at 2.server-bundle.js:760:1212
    at a.pe [as _l] (E:\workspace\blog\node_modules\vue\dist\vue.runtime.common.prod.js:6:15705)
    at a.PostsListItemvue_type_template_id_5daace0f_render (node_modules/vuepress-theme-meteorlxy/lib/components/PostsListItem.vue?385c:1:1056)
    at a.t._render (E:\workspace\blog\node_modules\vue\dist\vue.runtime.common.prod.js:6:34798)
    at E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:69946
    at Zi (E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:66510)
    at eo (E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:69922)
    at Qi (E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:69553)
    at yt.Xi [as renderNode] (E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:66800)
    at yt.next (E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:20384)
    at yt.n [as write] (E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:18596)
    at yt.next (E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:20467)
    at n (E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:18596)
    at E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:66621
    at yt.Xi [as renderNode] (E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:66772)
    at yt.next (E:\workspace\blog\node_modules\vue-server-renderer\build.prod.js:1:20384)
```
问题导向了PostsListItem.vue组件
2. 建议：希望能添加右侧导航在滚动到锚点时的样式，加强一下用户体验 :)

**Comment by meteorlxy** [comment]
第一个问题应该是没设置tags和category报错吧？

好吧我没能复现，最好多提供点信息

**Comment by baixiaoyu2997** [comment]
我刚才试了一下  就是没写tag导致的，其他没写没问题
